#!/usr/bin/env python3
"""Relay the Docker-published port to Plannotator's local-only listener."""

import selectors
import socket
import socketserver
import sys


class RelayHandler(socketserver.BaseRequestHandler):
    def handle(self) -> None:
        try:
            target = socket.create_connection(("127.0.0.1", self.server.target_port))
        except OSError:
            return

        with target:
            selector = selectors.DefaultSelector()
            selector.register(self.request, selectors.EVENT_READ, target)
            selector.register(target, selectors.EVENT_READ, self.request)
            try:
                while True:
                    events = selector.select()
                    for key, _ in events:
                        destination = key.data
                        data = key.fileobj.recv(65536)
                        if not data:
                            return
                        destination.sendall(data)
            finally:
                selector.close()


class RelayServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True

    def __init__(self, listen_port: int, target_port: int) -> None:
        self.target_port = target_port
        super().__init__(("0.0.0.0", listen_port), RelayHandler)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: plannotator-relay LISTEN_PORT TARGET_PORT")
    with RelayServer(int(sys.argv[1]), int(sys.argv[2])) as server:
        server.serve_forever()
