[settings]
auto_install = false
experimental = true

[task_config]
includes = ["tasks/*.toml"]

[tools]
"aqua:awslabs/git-secrets"       = "1.3.0"
"aqua:evilmartians/lefthook"     = "2.1.9"
"aqua:rhysd/actionlint"          = "1.7.12"
"aqua:secretlint/secretlint"     = "13.0.2"
"aqua:suzuki-shunsuke/ghalint"   = "1.5.6"
"aqua:suzuki-shunsuke/pinact"    = "4.0.0"
"aqua:tamasfe/taplo"             = "0.10.0"
"aqua:zizmorcore/zizmor"         = "1.25.2"
"github:betterleaks/betterleaks" = "1.3.1"
"github:superfly/flyctl"         = "0.4.29"
"npm:oxfmt"                      = "0.52.0"
# oxfmt                            = { version = "1.66.0", version_prefix = "apps_v", asset_pattern = "oxfmt-*", bin = "oxfmt" }
# oxlint                           = { version = "1.66.0", version_prefix = "apps_v", asset_pattern = "oxlint-*", bin = "oxlint" }

# [tool_alias]
# oxfmt  = "github:oxc-project/oxc"
# oxlint = "github:oxc-project/oxc"

[hooks]
enter = "lefthook install -f"
