[settings]
auto_install = false
experimental = true

[task_config]
includes = ["tasks/*.toml"]

[tools]
"aqua:evilmartians/lefthook"   = "2.1.4"
"aqua:rhysd/actionlint"        = "1.7.12"
"aqua:secretlint/secretlint"   = "11.7.1"
"aqua:suzuki-shunsuke/ghalint" = "1.5.6"
"aqua:suzuki-shunsuke/pinact"  = "3.10.1"
"aqua:tamasfe/taplo"           = "0.10.0"
"aqua:zizmorcore/zizmor"       = "1.24.1"
"github:superfly/flyctl"       = "0.4.29"
"npm:prettier"                 = "3.8.1"

[hooks]
enter = "lefthook install -f"
