["fix:all"]
depends     = ["fix:*"]
description = "Run all formatters"

["fix:action"]
description = "Run fix actions files"
run = [
    "GITHUB_TOKEN=${GITHUB_TOKEN:-$(ghtkn get)} pinact run",
    "disable-checkout-persist-credentials",
]

["fix:pinact"]
description = "Run pinact (fix)"
run         = "GITHUB_TOKEN=${GITHUB_TOKEN:-$(ghtkn get)} pinact run"

["fix:toml"]
description = "Run fix TOML files"
hide        = true
run         = "taplo format"

["fix:yaml"]
description = "Run fix YAML files"
hide        = true
run         = "oxfmt --disable-nested-config '**/*.{yaml,yml}'"

["fix:json"]
description = "Run fix JSON files"
hide        = true
run         = "oxfmt --disable-nested-config '**/*.json'"

["fix:md"]
description = "Run fix Markdown files"
hide        = true
run         = "oxfmt --disable-nested-config '**/*.md'"
