["karabiner:apply"]
description = "build and apply karabiner.ts configuration"
run         = ["mise run karabiner:dry-run", "bun config/karabiner-ts/karabiner.ts"]

["karabiner:dry-run"]
description = "build and dry-run karabiner.ts configuration"
run = [
    "bun config/karabiner-ts/karabiner.ts --dry-run > config/karabiner-ts/karabiner.json",
    "oxfmt config/karabiner-ts/karabiner.json",
]
