[settings]
auto_install = false
experimental = true

[tools]
"aqua:BurntSushi/ripgrep"        = "15.1.0"
"aqua:anthropics/claude-code"    = "2.1.168"
"aqua:astral-sh/uv"              = "0.11.15"
"aqua:cli/cli"                   = "2.93.0"
"aqua:golangci/golangci-lint"    = "2.12.2"
"aqua:koalaman/shellcheck"       = "0.11.0"
"aqua:mvdan/sh"                  = "3.13.1"
"aqua:openai/codex"              = "0.130.0"
"aqua:tamasfe/taplo"             = "0.10.0"
bun                              = "1.3.14"
"github:github/copilot-cli"      = "1.0.59"
"github:philschmid/mcp-cli"      = { version = "0.3.0", asset_pattern = "mcp-cli-linux-x64" }
go                               = "1.26.4"
node                             = "22.19.0"
"npm:@google/gemini-cli"         = "0.43.0"
"npm:@typescript/native-preview" = "7.0.0-dev.20260519.1"
"npm:ccusage"                    = "20.0.1"
"npm:oxfmt"                      = "0.53.0"
# oxfmt                            = { version = "1.66.0", version_prefix = "apps_v", asset_pattern = "oxfmt-*", bin = "oxfmt" }
# oxlint                           = { version = "1.66.0", version_prefix = "apps_v", asset_pattern = "oxlint-*", bin = "oxlint" }
python = "3.14.3"

# [tool_alias]
# oxfmt  = "github:oxc-project/oxc"
# oxlint = "github:oxc-project/oxc"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
