[tools]
"aqua:Songmu/laminate"   = "0.0.4"
"aqua:k1LoW/deck"        = "1.24.1"
"aqua:supabase/cli"      = "2.114.0"
"github:render-oss/cli"  = { version = "2.15.1", rename_exe = "render" }
"github:superfly/flyctl" = "0.4.29"

[bootstrap.packages]
# 実際に WSL を使い始めたら bootstrap-mac.toml 側への切り出しを検討する
"brew-cask:android-studio" = "latest" # 2026.1.3.7,quail3,AI-261.26222.65.2613.15948027
"brew-cask:insomnia"       = "latest" # 13.1.0
"brew-cask:linear"         = "latest" # 1.32.1
"brew:ffmpeg"              = "latest" # 8.1.2
