[tools]
"aqua:Songmu/ecschedule"                    = "0.17.2"
"aqua:aquasecurity/trivy"                   = "0.69.3"
"aqua:ariga/atlas"                          = "0.37.0"
"aqua:aws/aws-cli"                          = "2.34.21"
"aqua:direnv/direnv"                        = "2.37.1"
"aqua:kayac/ecspresso"                      = "2.8.0"
"aqua:keidarcy/e1s"                         = "1.0.53"
"aqua:leg100/pug"                           = "0.6.5"
"aqua:rclone/rclone"                        = "1.73.4"
"aqua:terraform-linters/tflint"             = "0.61.0"
"go:github.com/99designs/gqlgen"            = "0.17.89"
"go:github.com/lusingander/gotip/cmd/gotip" = "0.6.2"
"go:gotest.tools/gotestsum"                 = "1.13.0"
"pipx:awslogs"                              = "0.15.0"
"pipx:tftui"                                = "0.13.4"
"postgres"                                  = "14.19"
terraform                                   = "1.14.8"
