[tools]
"aqua:aquasecurity/trivy"                   = "0.71.2"
"aqua:aws/aws-cli"                          = "2.34.21"
"aqua:direnv/direnv"                        = "2.37.1"
"aqua:hashicorp/terraform"                  = "1.15.4"
"aqua:keidarcy/e1s"                         = "1.0.53"
"aqua:leg100/pug"                           = "0.6.5"
"aqua:rclone/rclone"                        = "1.74.3"
"aqua:terraform-linters/tflint"             = "0.63.1"
"github:ByteNess/aws-vault"                 = "7.12.1"
"github:huseyinbabal/taws"                  = "1.3.0-rc.8"
"go:github.com/lusingander/gotip/cmd/gotip" = "0.7.0"
"go:gotest.tools/gotestsum"                 = "1.13.0"
"pipx:awslogs"                              = "0.15.0"
"pipx:tftui"                                = "0.13.4"

[settings]
trusted_config_paths = [
    "~/work",
]
