[[snippets]]
name    = "ccmanager"
snippet = "ccmanager"
trigger = "ccm"

[[snippets]]
name    = "ccmanager devcontainer"
snippet = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\""
trigger = "ccmc"

[[snippets]]
cursor          = "👇"
evaluate        = true
name            = "ccmanager devcontainer(claude account2)"
snippet         = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json env CLAUDE_CONFIG_DIR=/home/vscode/.claude-account2 claude --dangerously-skip-permissions\""
trigger-pattern = "(^ccmc2$|ccmcc2)"

[[snippets]]
name    = "devcontainer up"
snippet = "devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json"
trigger = "dcu"

[[snippets]]
cursor  = "👇"
name    = "devcontainer exec"
snippet = "devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json -- 👇"
trigger = "dce"

[[snippets]]
name    = "mcp-cli"
snippet = "mcp-cli -c ~/.copilot/mcp-config.json"
trigger = "mcp"

[[snippets]]
global  = true
name    = "claude"
snippet = "claude"
trigger = "cl"

[[snippets]]
global  = true
name    = "claude2"
snippet = "claude2"
trigger = "cl2"

[[snippets]]
global  = true
name    = "claude --dangerously-skip-permissions"
snippet = "claude --dangerously-skip-permissions"
trigger = "cly"

[[snippets]]
global  = true
name    = "copilot"
snippet = "copilot"
trigger = "co"

[[snippets]]
global  = true
name    = "copilot --yolo"
snippet = "copilot --yolo"
trigger = "coy"

[[snippets]]
global  = true
name    = "codex"
snippet = "codex"
trigger = "cx"

[[snippets]]
global  = true
name    = "codex --yolo"
snippet = "codex --yolo"
trigger = "cxy"

[[snippets]]
context = ".*claude(2)?\\s"
global  = true
name    = "(ccmanager) --multi-project"
snippet = "--multi-project"
trigger = "mp"

[[snippets]]
context = ".*claude(2)?\\s"
global  = true
name    = "(claude*) --dangerously-skip-permissions"
snippet = "--dangerously-skip-permissions"
trigger = "yl"

[[snippets]]
context = ".*(copilot|codex|gemini)\\s"
global  = true
name    = "(copilot|codex|gemini) --yolo"
snippet = "--yolo"
trigger = "yl"
