[[snippets]]
name            = "terraform"
snippet         = "terraform"
trigger-pattern = "^tf$"

[[snippets]]
name    = "terraform init"
snippet = "terraform init"
trigger = "tfi"

[[snippets]]
name    = "terraform plan"
snippet = "terraform plan"
trigger = "tfp"

[[snippets]]
name    = "terraform plan (Debug: All)"
snippet = "TF_LOG=DEBUG terraform plan"
trigger = "tfpd"

[[snippets]]
name    = "terraform plan (Debug: Core)"
snippet = "TF_LOG_CORE=DEBUG terraform plan"
trigger = "tfpdc"

[[snippets]]
name    = "terraform plan (Debug: Provider)"
snippet = "TF_LOG_PROVIDER=DEBUG terraform plan"
trigger = "tfpdp"

[[snippets]]
name    = "terraform apply"
snippet = "terraform apply"
trigger = "tfa"

[[snippets]]
name    = "terraform apply (Debug: All)"
snippet = "TF_LOG=DEBUG terraform apply"
trigger = "tfad"

[[snippets]]
name    = "terraform apply (Debug: Core)"
snippet = "TF_LOG_CORE=DEBUG terraform apply"
trigger = "tfadc"

[[snippets]]
name    = "terraform apply (Debug: Provider)"
snippet = "TF_LOG_PROVIDER=DEBUG terraform apply"
trigger = "tfadp"

[[snippets]]
name    = "terraform fmt -recursive"
snippet = "terraform fmt -recursive"
trigger = "tff"

[[snippets]]
name    = "terraform validate"
snippet = "terraform validate"
trigger = "tfv"

[[snippets]]
name    = "terraform show"
snippet = "terraform show"
trigger = "tfs"

[[snippets]]
name    = "terraform state"
snippet = "terraform state"
trigger = "tfst"

[[snippets]]
name    = "terraform workspace"
snippet = "terraform workspace"
trigger = "tfw"

[[snippets]]
name    = "terraform output"
snippet = "terraform output"
trigger = "tfo"
