[[snippets]]
name            = "terraform"
snippet         = "terraform"
trigger-pattern = "^tf$"

[[snippets]]
name    = "terraform init"
snippet = "terraform init"
trigger = "tfi"

[[snippets]]
name    = "terraform plan"
snippet = "terraform plan"
trigger = "tfp"

[[snippets]]
name    = "terraform apply"
snippet = "terraform apply"
trigger = "tfa"

[[snippets]]
name    = "terraform fmt -recursive"
snippet = "terraform fmt -recursive"
trigger = "tff"

[[snippets]]
name    = "terraform validate"
snippet = "terraform validate"
trigger = "tfv"

[[snippets]]
name    = "terraform show"
snippet = "terraform show"
trigger = "tfs"

[[snippets]]
name    = "terraform state"
snippet = "terraform state"
trigger = "tfst"

[[snippets]]
name    = "terraform workspace"
snippet = "terraform workspace"
trigger = "tfw"

[[snippets]]
name    = "terraform output"
snippet = "terraform output"
trigger = "tfo"

# terraform-tools
[[snippets]]
name    = "tflint"
snippet = "tflint"
trigger = "tfl"

[[snippets]]
name    = "tflint --init"
snippet = "tflint --init"
trigger = "tfli"

[[snippets]]
name    = "tflint --recursive"
snippet = "tflint --recursive"
trigger = "tflr"

[[snippets]]
name    = "tflint --fix"
snippet = "tflint --fix"
trigger = "tflf"

[[snippets]]
name    = "tftui"
snippet = "tftui"
trigger = "tft"

[[snippets]]
name    = "pug (tetui2)"
snippet = "pug"
trigger = "tft2"

# trivy
[[snippets]]
name    = "trivy"
snippet = "trivy"
trigger = "trv"

[[snippets]]
name    = "trivy image"
snippet = "trivy image"
trigger = "trvi"

[[snippets]]
name    = "trivy fs"
snippet = "trivy fs ."
trigger = "trvf"

[[snippets]]
name    = "trivy config"
snippet = "trivy config ."
trigger = "trvc"

[[snippets]]
name    = "trivy repo"
snippet = "trivy repo"
trigger = "trvr"
