autocomplete     = true
breaking_changes = false
emoji            = false
issues           = false
sign             = false

[[commit_types]]
description = "新機能"
name        = "feat"

[[commit_types]]
description = "その他(雑多な対応)"
name        = "chore"

[[commit_types]]
description = "バグ修正"
name        = "fix"

[[commit_types]]
description = "リファクタリングのための変更(機能追加やバグ修正を含まない)"
name        = "refactor"

[[commit_types]]
description = "作業途中"
name        = "wip"

[[commit_types]]
description = "テスト"
name        = "test"
