have_fun: false

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  auto_resolve_conversations: true
  max_review_comments: 20
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: false

ignore_patterns:
  - "not_config/**"
  - "dot_config/sidebery/**"
  - "dot_config/dbeaver/**"
  - "dot_config/raycast/**"
