[tools]
"aqua:aws/aws-cli"           = "2.37.7"
"aqua:pre-commit/pre-commit" = "4.6.2"
java                         = "temurin-21"

[bootstrap.packages]
"brew:libpq"     = "latest" # 18.6
"brew:openssl@3" = "latest" # 3.6.5

[settings]
trusted_config_paths = [
    "~/Programming/work3",
]
