name: benchmark

on: [push,workflow_dispatch]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write


jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)"

    - run: chezmoi apply $HOME/.{zshrc,zshrc.lazy,zshenv,zprofile}

    - run: |
        cat $HOME/.zshrc
        cat $HOME/.zshrc.lazy
        cat $HOME/.zshenv
        cat $HOME/.zprofile

    # - name: Run benchmark
    #   run: ./scripts/benchmark.sh > result.json

    # - name: Dump result.json
    #   run: cat result.json

    # - name: Upload benchmark
    #   uses: benchmark-action/github-action-benchmark@v1
    #   with:
    #     tool: customSmallerIsBetter
    #     output-file-path: result.json
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     auto-push: true
    #     comment-on-alert: true
    #     fail-on-alert: true
    #     alert-threshold: '150%'
    #     alert-comment-cc-users: '@odanado'
