name: deploy-atuin
on:
  push:
    branches:
      - main
    paths:
      - dot_config/atuin/fly.toml
  workflow_dispatch:

permissions: {}

concurrency:
  group: deploy-atuin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Atuin to Fly.io
    runs-on: ubuntu-slim
    environment: production
    permissions:
      contents: read
    timeout-minutes: 10
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install_args: "github:superfly/flyctl"
      - name: Deploy Atuin
        run: flyctl deploy --app ryo-shellhistory -c dot_config/atuin/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
