name: lint-action
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

permissions: {}

concurrency:
  group: lint-action-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ ! endsWith(github.actor, '[bot]')}}
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install_args: "aqua:rhysd/actionlint aqua:suzuki-shunsuke/ghalint pipx:zizmor"
        env:
          MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
      - name: actionlint
        run: |
          actionlint \
          -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' \
          -ignore 'SC2016:'
      - name: ghalint
        if: always()
        run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
      - name: zizmor
        if: always()
        run: zizmor --config zizmor.yml --pedantic --format=github --min-severity=low .github/workflows
        env:
          GH_TOKEN: ${{ github.token }}
