name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ ! endsWith(github.actor, '[bot]')}}
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            json:
              - "**/*.json"
            yaml:
              - "**/*.yaml"
              - "**/*.yml"
            md:
              - "**/*.md"
            toml:
              - "**/*.toml"
            actions:
              - ".github/workflows/*"
            secret:
              - "**/*"

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install_args: "aqua:rhysd/actionlint aqua:secretlint/secretlint aqua:suzuki-shunsuke/ghalint aqua:suzuki-shunsuke/pinact aqua:tamasfe/taplo aqua:zizmorcore/zizmor npm:oxfmt"
        env:
          MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s

      - name: oxfmt (json)
        if: steps.changed-files.outputs.json_any_changed == 'true'
        run: mise run lint:json

      - name: oxfmt (yaml)
        if: always() && steps.changed-files.outputs.yaml_any_changed == 'true'
        run: mise run lint:yaml

      - name: oxfmt (markdown)
        if: always() && steps.changed-files.outputs.md_any_changed == 'true'
        run: mise run lint:md

      - name: taplo (toml)
        if: always() && steps.changed-files.outputs.toml_any_changed == 'true'
        run: mise run lint:toml

      - name: actionlint
        if: always() && steps.changed-files.outputs.actions_any_changed == 'true'
        run: mise run lint:actionlint

      - name: ghalint
        if: always() && steps.changed-files.outputs.actions_any_changed == 'true'
        run: mise run lint:ghalint
        env:
          GHALINT_LOG_COLOR: always

      - name: zizmor
        if: always() && steps.changed-files.outputs.actions_any_changed == 'true'
        run: mise run lint:zizmor
        env:
          GH_TOKEN: ${{ github.token }}

      - name: pinact
        if: always() && steps.changed-files.outputs.actions_any_changed == 'true'
        run: mise run lint:pinact

      - name: secretlint
        if: always() && steps.changed-files.outputs.secret_any_changed == 'true'
        run: mise run lint:secret
